### ISSUE TITLE
Have a more descriptive name for the default manifest file?

### ISSUE THREAD

**Issue by hcpss-mbarger** [HCPSS/tasc#1]
There have been a few times when I've accidentally overlooked a TASC manifest since it has such a simple filename, `manifest.yml`.  What would you think of the default name being `tasc-manifest.yml` so that it visually stands out when browsing a project?

**Comment by hcpss-banderson** [comment]
What about `Tascfile`?

**Comment by hcpss-mbarger** [comment]
Works for me.  Will it be `tascfile.yaml`?

**Comment by hcpss-banderson** [comment]
I kind of like how `Dockerfile` and `Vagrantfile` communicate their importance and define a context. Originally, the manifest did define a context. Patches and local files had to be in the same directory. It was more convenience than planning and I have since added flexibility so patches and local files can be anywhere. But maybe TASC should be opinionated about not doing that.

So anyway does `Dockerfile` communicate it's importance and context defining power by starting with a capitol letter and not having an extension? I think so, but I am not up on the psychology of file naming :)

**Comment by hcpss-mbarger** [comment]
Gotcha, now I'm seeing the implied similarity.  

Hmm. I think either way you have the context bundled up nicely.  My question would be - do you see TASC files as a control language (Vagrant or Docker) or a configuration language (like Ansible)? Right now I see it more as a config language, but if you think you may add a `run` or `build` section in the future, I'd go with `Tascfile` now to future proof it.

I used to always advocate for file extensions for Windows portability but I'm not sure that is as much of an issue now with the success of Docker and Vagrant and Microsoft's subsequent embrace of a bunch of Unix-isms.

I'm really jazzed about TASC, so as long as `tasc` is in the default filename, I'd be happy with either direction actually.  Whichever you feel captures the intention (and possible future intentions) best.

**Comment by hcpss-banderson** [comment]
Ended up going with tasc-manifest.yml after all. The manifest is configuration, not control and the inspiration for this project is drush make which use something similar.
